# Generated by Django 5.0.2 on 2024-02-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='neme',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
