# Generated by Django 5.0.2 on 2024-02-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_model_product_price_product_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='neme',
            new_name='name',
        ),
    ]
