# Generated by Django 5.0.2 on 2024-02-23 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('product', '0005_product_catergory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.ForeignKey(choices=[(1, 'Azoom Movies'), (2, 'kjldajkljjds')], on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
